// <auto-generated />
using CardFileCore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CardFileCore.Migrations.Application
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20180414144022_Uno")]
    partial class Uno
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CardFileCore.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Number");

                    b.HasKey("Id");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("CardFileCore.Models.BookQuery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BookName");

                    b.Property<string>("UserName");

                    b.Property<DateTime>("Validity");

                    b.HasKey("Id");

                    b.ToTable("BookQueries");
                });

            modelBuilder.Entity("CardFileCore.Models.GivenBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BookName");

                    b.Property<string>("UserName");

                    b.Property<DateTime>("Validity");

                    b.HasKey("Id");

                    b.ToTable("GivenBooks");
                });
#pragma warning restore 612, 618
        }
    }
}
